"""add unique constraint on pull_requests

Revision ID: 4b874a934928
Revises: e76ae9524fd3
Create Date: 2026-03-24 16:05:30.549563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b874a934928'
down_revision: Union[str, Sequence[str], None] = 'e76ae9524fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_pull_requests_project_github_pr', 'pull_requests', ['project_id', 'github_pr_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_pull_requests_project_github_pr', 'pull_requests', type_='unique')
    # ### end Alembic commands ###
