"""add AI models and PR branch refs

Revision ID: 7477127634ab
Revises: 4b874a934928
Create Date: 2026-03-24 20:18:42.853262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7477127634ab'
down_revision: Union[str, Sequence[str], None] = '4b874a934928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_briefings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('org_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('project_briefings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='briefingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_briefings_org_id'), 'weekly_briefings', ['org_id'], unique=False)
    op.create_table('ai_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('pull_request_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('code_review', 'analysis', 'test_scenario', name='aireviewtype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='aireviewstatus'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('github_comment_id', sa.Integer(), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_reviews_project_id'), 'ai_reviews', ['project_id'], unique=False)
    op.create_table('ai_job_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.Enum('code_review', 'analysis', 'briefing', 'test_scenario', name='jobtype'), nullable=False),
    sa.Column('trigger', sa.Enum('webhook', 'schedule', 'manual', name='jobtrigger'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='jobstatus'), nullable=False),
    sa.Column('ai_review_id', sa.UUID(), nullable=True),
    sa.Column('briefing_id', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ai_review_id'], ['ai_reviews.id'], ),
    sa.ForeignKeyConstraint(['briefing_id'], ['weekly_briefings.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pull_requests', sa.Column('base_ref', sa.String(), nullable=True))
    op.add_column('pull_requests', sa.Column('head_ref', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pull_requests', 'head_ref')
    op.drop_column('pull_requests', 'base_ref')
    op.drop_table('ai_job_queue')
    op.drop_index(op.f('ix_ai_reviews_project_id'), table_name='ai_reviews')
    op.drop_table('ai_reviews')
    op.drop_index(op.f('ix_weekly_briefings_org_id'), table_name='weekly_briefings')
    op.drop_table('weekly_briefings')
    # ### end Alembic commands ###
