"""add progress_log to ai_job_queue

Revision ID: d29d8a0f7510
Revises: 16126a08cea5
Create Date: 2026-03-25 10:26:54.259123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd29d8a0f7510'
down_revision: Union[str, Sequence[str], None] = '16126a08cea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_job_queue', sa.Column('progress_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_job_queue', 'progress_log')
    # ### end Alembic commands ###
